### PR TITLE
Add Neurable, move Trove

### PR DESCRIPTION
**Pull request by dugsong**
Conflicted about this, but you didn't accept my pull request to remove Avegant, a company that started here and left, so I'm adding Neurable - Ramses was an a2newtech attendee who did great with Neurable, but took the team to Boston.

Also moving Trove to keep this list alphabetical!

### CODE REVIEW

**Comment by sampl** [comment]
not sure what happened... LGTM, merge away 👍

**Comment by sampl** [comment]
Taking another look here--obviously didn't read it carefully the first time. 

The guidelines we have for location in the readme are:

> Location: A company must have the majority of employees working in Ann Arbor or have a branch with a founder and another full time employee here.

Based on this, I think ex-Ann Arbor orgs probably shouldn't be included (ie don't merge Neurable and remove Avegant). This is also in line with our goals for MIA2--demonstrate the activity of the tech scene for employees and founders looking to grow here.

**Comment by sampl** [comment]
since @andrewsardone offered to clean up the alpha ordering with a new PR, closing for now--but we're open to hearing other thoughts on this!

**Comment by andrewsardone** [comment]
> I think ex-Ann Arbor orgs probably shouldn't be included (ie don't merge Neurable and remove Avegant)

👍 alright, we're now live without Avegant:

<kbd>screenshot 2017-10-27 12 35 02</kbd>

**Pull request closed without merging**
