### PR TITLE
Added Saganworks

### PR DESCRIPTION
**Pull request by lumbernauts**

### CODE REVIEW

**Comment by sampl** [comment]
@lumbernauts thanks for adding. Can you comment on whether Saganworks meets the traction aspect of the company requirements? https://github.com/MadeInA2/madeina2/blob/master/README.md

If it is too early for Saganworks to be listed, we can close and reopen the PR later.

**Comment by lumbernauts** [comment]
Hi @sampl, we haven't yet launched publicly, but we've raised a seed round and are actively looking for additional developers. Thanks!

**Comment by sampl** [comment]
Sounds like you’re a bit too early—reopen this when you launch!

**Comment by briankelly** [comment]
Scratch this PR. I'll open a new one for Saganworks.

**Comment by briankelly** [comment]
Done. See PR #83.

**Pull request closed without merging**
